NL = chr(10)
Q = chr(34)
BS = chr(92)
L = []
def w(s): L.append(s)

w('import sys')
w('sys.stdout.reconfigure(encoding="utf-8", errors="replace")')
w('import paramiko, base64')
w('')
w('HOST = "88.99.142.89"')
w('PORT = 22')
w('USER = "root"')
w('PASSWORD = "uhKs54?u__WdiN"')
w('')
w('')
w('def run(client, cmd, timeout=30):')
w('    print("\\n[CMD] " + cmd[:120])')
w('    stdin, stdout, stderr = client.exec_command(cmd, timeout=timeout)')
w('    out = stdout.read().decode("utf-8", errors="replace").strip()')
w('    err = stderr.read().decode("utf-8", errors="replace").strip()')
w('    rc = stdout.channel.recv_exit_status()')
w('    if out:')
w('        print("[OUT] " + out)')
w('    if err:')
w('        print("[ERR] " + err)')
w('    print("[RC]  " + str(rc))')
w('    return out, err, rc')
w('')
w('')
w('def wrf(client, path, content):')
w('    b64 = base64.b64encode(content.encode("utf-8")).decode("ascii")')
w('    return run(client, "echo " + b64 + " | base64 -d > " + path)')
w('')

TARGET = 'C:/Users/asus/Desktop/projects/gifmake/scripts/enable_openssh_rescue.py'
with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(NL.join(L) + NL)
print('Helper functions written to ' + TARGET)
