OUT = 'C:/Users/asus/Desktop/projects/gifmake/scripts/enable_openssh_rescue.py'
NL = chr(10)
SQ = chr(39)
BS = chr(92)
DQ = chr(34)
NE = chr(33) + chr(61)
code = []
A = code.append
A('    # Step 3: SYSTEM hive - sshd + ssh-agent Automatic')
A("    print('\\n--- Step 3: Enable sshd + ssh-agent in SYSTEM hive ---')")
A('    CRNL = chr(13) + chr(10)')
A('    DQ = chr(34)')
A('    sshd_reg = (')
A("        'Windows Registry Editor Version 5.00' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet001\\\\\\\\Services\\\\\\\\sshd]' + CRNL")
A("        + DQ + 'Start' + DQ + '=dword:00000002' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet001\\\\\\\\Services\\\\\\\\ssh-agent]' + CRNL")
A("        + DQ + 'Start' + DQ + '=dword:00000002' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet002\\\\\\\\Services\\\\\\\\sshd]' + CRNL")
A("        + DQ + 'Start' + DQ + '=dword:00000002' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet002\\\\\\\\Services\\\\\\\\ssh-agent]' + CRNL")
A("        + DQ + 'Start' + DQ + '=dword:00000002' + CRNL + CRNL")
A('    )')
A("    wrf(client, '/tmp/sshd.reg', sshd_reg)")
A('    out, err, rc = run(')
A('        client,')
A("        'reged -I -C /mnt/win/Windows/System32/config/SYSTEM '")
A("        + chr(39) + 'HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM' + chr(39) + ' /tmp/sshd.reg 2>&1'")
A('    )')
A("    if rc == 0 or 'done' in (out + err).lower():")
A("        print('[+] SYSTEM hive: sshd + ssh-agent = Automatic (Start=2)')")
A('    else:')
A("        print('[WARN] reged SYSTEM rc=' + str(rc) + ' | ' + out[:200])")
A('')
A('    # Step 4: SOFTWARE hive RunOnce')
A("    print('\\n--- Step 4: Add RunOnce entries in SOFTWARE hive ---')")
A('    runonce_reg = (')
A("        'Windows Registry Editor Version 5.00' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SOFTWARE\\\\\\\\Microsoft\\\\\\\\Windows\\\\\\\\CurrentVersion\\\\\\\\RunOnce]' + CRNL")
A("        + DQ + 'SetupSSH' + DQ + '=' + DQ + 'cmd.exe /c net start sshd & netsh advfirewall firewall add rule name=SSH dir=in action=allow protocol=TCP localport=22' + DQ + CRNL")
A("        + DQ + 'SetupSSHAgent' + DQ + '=' + DQ + 'cmd.exe /c net start ssh-agent' + DQ + CRNL + CRNL")
A('    )')
A("    wrf(client, '/tmp/ssh_runonce.reg', runonce_reg)")
A('    out, err, rc = run(')
A('        client,')
A("        'reged -I -C /mnt/win/Windows/System32/config/SOFTWARE '")
A("        + chr(39) + 'HKEY_LOCAL_MACHINE\\\\\\\\SOFTWARE' + chr(39) + ' /tmp/ssh_runonce.reg 2>&1'")
A('    )')
A("    if rc == 0 or 'done' in (out + err).lower():")
A("        print('[+] SOFTWARE hive: RunOnce SetupSSH + SetupSSHAgent added')")
A('    else:')
A("        print('[WARN] RunOnce reg rc=' + str(rc) + ' | ' + out[:200])")
A('')
A('    # Step 5: SYSTEM hive Firewall rule for SSH port 22')
A("    print('\\n--- Step 5: Add SSH firewall rule to SYSTEM hive ---')")
A('    fw_reg = (')
A("        'Windows Registry Editor Version 5.00' + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet001\\\\\\\\Services\\\\\\\\SharedAccess\\\\\\\\Parameters\\\\\\\\FirewallPolicy\\\\\\\\FirewallRules]' + CRNL")
A("        + DQ + 'SSH-In-TCP' + DQ + '=' + DQ + 'v2.30|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=22|Name=SSH|Desc=OpenSSH Server|' + DQ + CRNL + CRNL")
A("        + '[HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM\\\\\\\\ControlSet002\\\\\\\\Services\\\\\\\\SharedAccess\\\\\\\\Parameters\\\\\\\\FirewallPolicy\\\\\\\\FirewallRules]' + CRNL")
A("        + DQ + 'SSH-In-TCP' + DQ + '=' + DQ + 'v2.30|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=22|Name=SSH|Desc=OpenSSH Server|' + DQ + CRNL + CRNL")
A('    )')
A("    wrf(client, '/tmp/ssh_fw.reg', fw_reg)")
A('    out, err, rc = run(')
A('        client,')
A("        'reged -I -C /mnt/win/Windows/System32/config/SYSTEM '")
A("        + chr(39) + 'HKEY_LOCAL_MACHINE\\\\\\\\SYSTEM' + chr(39) + ' /tmp/ssh_fw.reg 2>&1'")
A('    )')
A("    if rc == 0 or 'done' in (out + err).lower():")
A("        print('[+] SYSTEM hive: Firewall rule SSH port 22 added (CS001+CS002)')")
A('    else:')
A("        print('[WARN] SSH FW reg rc=' + str(rc) + ' | ' + out[:200])")
A('')
A('    # Step 6: Verify sshd Start value')
A("    print('\\n--- Step 6: Verify sshd Start value ---')")
A('    vcmd = (')
A("        'printf '")
A("        + chr(39) + 'cd ControlSet001\\\\\\\\\\\\\\\\Services\\\\\\\\\\\\\\\\sshd\\\\\\\\ncat Start\\\\\\\\nq\\\\\\\\nn\\\\\\\\n' + chr(39)")
A("        + ' | chntpw -e /mnt/win/Windows/System32/config/SYSTEM 2>&1'")
A('    )')
A('    out, err, rc = run(client, vcmd)')
A("    if '0x2' in out or ': 2' in out:")
A("        print('[+] Verified: sshd Start = 0x2 (Automatic)')")
A('    else:')
A("        print('[INFO] sshd verify output: ' + out[:300])")
A('')
A('    # Step 7: Sync')
A("    print('\\n--- Step 7: Sync filesystem (NOT unmounting) ---')")
A("    run(client, 'sync')")
A("    print('[+] Sync done. Partition stays mounted at /mnt/win.')")
A('')
A('    # Summary')
A("    print('\\n============================================================')")
A("    print('FINAL SUMMARY')")
A("    print('============================================================')")
A("    print('OpenSSH sshd.exe present : ' + ('YES' if sshd_exists else 'NO - OpenSSH not installed'))")
A("    print('SYSTEM hive sshd         : Start=2 (Automatic) CS001+CS002')")
A("    print('SYSTEM hive ssh-agent    : Start=2 (Automatic) CS001+CS002')")
A("    print('SYSTEM hive FW rule      : SSH port 22 ALLOW (CS001+CS002)')")
A("    print('SOFTWARE RunOnce         : SetupSSH + SetupSSHAgent')")
A("    print('Partition                : Mounted at /mnt/win (NOT unmounted)')")
A("    print('')")
A('    if sshd_exists:')
A("        print('RESULT: Deactivate rescue mode in Hetzner Robot and reboot.')")
A("        print('        SSH access:   ssh Administrator@88.99.142.89 -p 22')")
A("        print('        No rescue mode needed for future access.')")
A('    else:')
A("        print('RESULT: OpenSSH not installed on Windows.')")
A("        print('        After Windows boots, run in PowerShell (Admin):')")
A("        print('          Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0')")
A("        print('          Then reboot - RunOnce will start sshd automatically.')")
A('    client.close()')
A("    print('\\n[*] Paramiko session closed.')")
A('')
A('')
A("if __name__ == '__main__':")
A('    main()')

with open(OUT, 'a', encoding='utf-8') as fout:
    fout.write(NL.join(code) + NL)
print('Part2 appended: ' + str(len(code)) + ' lines')
